### ISSUE TITLE
No TXT Record Found

### ISSUE THREAD

**Issue by norsemangrey** [domeneshop/certbot-dns-domeneshop#1]
I get a "No TXT record found at _acme-challenge.<my domain>.no" when attempting to run the plugin. Not sure why, but the challenge seems to run two times. Output from log below:

```
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for <my domain>.no
dns-01 challenge for <my domain>.no
Unsafe permissions on credentials configuration file: /config/dns-conf/domeneshop.ini
Waiting 60 seconds for DNS changes to propagate
Waiting for verification...
Challenge failed for domain <my domain>.no
Challenge failed for domain <my domain>.no
dns-01 challenge for <my domain>.no
dns-01 challenge for <my domain>.no
Cleaning up challenges
Some challenges have failed.
IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: <my domain>.no
   Type:   unauthorized
   Detail: No TXT record found at _acme-challenge.<my domain>.no

   Domain: <my domain>.no
   Type:   unauthorized
   Detail: No TXT record found at _acme-challenge.<my domain>.no

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.
```

**Comment by eirikrye** [comment]
Hi,

We are missing some information in order to troubleshoot this. What is the certbot command you are running?

Certbot should not create multiple challenges for the same FQDN. If it does, then that is outside the scope of this plugin and should be reported to Certbot.

In any case, the default propagation time of 60 seconds is unfortunately not always enough for the DNS changes to propagate in some cases. I would suggest upping it to 120 seconds to ensure that changes have propagated. You can do this by providing the following command line argument to Certbot:

`--certbot-dns-domeneshop:dns-domeneshop-propagation-seconds 120`

**Comment by norsemangrey** [comment]
See below the Certbot command:

```
ACMESERVER="https://acme-v02.api.letsencrypt.org/directory"

EMAILPARAM="-m <my email address> --no-eff-email"

export URL_REAL="-d *.<my domain url> -d <my domain url>"

PREFCHAL="-a certbot-dns-domeneshop:dns-domeneshop --certbot-dns-domeneshop:dns-domeneshop-credentials /config/dns-conf/domeneshop.ini --manual-public-ip-logging-ok"

certbot certonly --renew-by-default --server $ACMESERVER $PREFCHAL --rsa-key-size 4096 $EMAILPARAM --agree-tos $URL_REAL
```

I will check if it is possible to provide the increased propagation time parameter.

**Comment by eirikrye** [comment]
Your wildcard domain in addition to the apex domain explains the duplicate challenges. The missing records I assume will be resolved by increasing the propagation time.

**Comment by norsemangrey** [comment]
Thanks for the clarification. I have got it working now.
