### ISSUE TITLE
--certbot-dns-domeneshop:dns-domeneshop-credentials not read by certbot

### ISSUE THREAD

**Issue by roflmao** [domeneshop/certbot-dns-domeneshop#2]
```
# certbot certonly \
>   --authenticator dns-domeneshop \
>   --certbot-dns-domeneshop:dns-domeneshop-credentials /root/.secrets/domeneshop.ini \
>   --certbot-dns-domeneshop:dns-domeneshop-propagation-seconds 120 \
>   -d mon.yo.lo
^[[3~Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-domeneshop, Installer None
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for mon.yo.lo
Cleaning up challenges
File not found: /etc/letsencrypt/domeneshop.ini
```

```
# certbot --version
certbot 1.8.0
```

```
# pip list
<snip>
certbot-dns-domeneshop (0.2.8)
domeneshop (0.4.2)
```

**Comment by roflmao** [comment]
Also the format of the credentials files have changed. certbot 1.8.0 breaking change?

New format:
```
# cat /etc/letsencrypt/domeneshop.ini
dns_domeneshop_client_token=XXX
dns_domeneshop_client_secret=XXX
```

**Comment by eirikrye** [comment]
Hi, thanks for the report!

You appear to be correct. Certbot no longer requires the arguments and credential files to have their keys prefixed with the plugin name.

For your command line arguments, `--dns-domeneshop-credentials` and `--dns-domeneshop-propagation-seconds` should work now.

We will update the documentation as soon as we can find the documentation of this change in Certbot...

**Comment by eirikrye** [comment]
The change is documented [here](https://github.com/certbot/certbot/releases/tag/v1.7.0) (Certbot 1.7.0), stating that the prefix form is deprecated but still supported. It evidently is **not** still supported, though.

**Comment by eirikrye** [comment]
The change is documented [here](https://github.com/certbot/certbot/releases/tag/v1.7.0) (certbot 1.7.0), which states the old prefix syntax is still supported.

The reason it does not work for you is because you are mixing the prefixed form with the non-prefixed form in the `--authenticator` argument. If you use `--authenticator certbot-dns-domeneshop:dns-domeneshop` it will also expect the prefixed arguments and credentials file. Likewise, when using `--authenticator dns-domeneshop` (the new behavior), you should use non-prefixed arguments and credentials.

**Comment by roflmao** [comment]
Thanks!
